version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: virtual_file_system
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
